package org.inf.ty;

public enum TyDiffKind {

  INCOMPATIBLE,
  DIFF_RADIX,
  DIFF_SIGNED,
  DIFF_WIDTH_EXT,
  DIFF_WIDTH_TRUNC,
  DIFF_WIDTH_EXPLICIT,
  DIFF_PRECISION_EXT,
  DIFF_PRECISION_TRUNC,
  UNKNOWN
}
